package FormDatBan;

import Model.ModelKH;
import Repository.Repository;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

public class MS_ConfirmCustomer extends javax.swing.JDialog {
    
    private Repository rp = new Repository();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = -1;
    private DecimalFormat df;
    private ArrayList<ModelKH> allKhachhang;
    private BookingTable bookingTable;

    public MS_ConfirmCustomer(java.awt.Frame parent, boolean modal, BookingTable bookingTable) {
        super(parent, modal);
        initComponents();
        this.bookingTable = bookingTable;
        allKhachhang = rp.getAll();
        this.filltable(allKhachhang);
        i = allKhachhang.size();
        tbl_KhachHang.setRowSelectionInterval(i - 1, i - 1);
        rp = new Repository();
        mol = (DefaultTableModel) tbl_KhachHang.getModel();

        // Add DocumentListener to txtSearch
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                searchTable(txtSearch.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                searchTable(txtSearch.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                searchTable(txtSearch.getText());
            }
        });
    }

    void filltable(ArrayList<ModelKH> list) {
        mol = (DefaultTableModel) tbl_KhachHang.getModel();
        mol.setRowCount(0);
        for (ModelKH x : list) {
            mol.addRow(x.toDaTaRow());
        }
    }

    private void searchTable(String query) {
        ArrayList<ModelKH> filteredList = (ArrayList<ModelKH>) allKhachhang.stream()
                .filter(kh -> kh.getTen().toLowerCase().contains(query.toLowerCase())
                        || kh.getSodt().toLowerCase().contains(query.toLowerCase())
                        || kh.getEmail().toLowerCase().contains(query.toLowerCase())
                        || kh.getDiachi().toLowerCase().contains(query.toLowerCase()))
                .collect(Collectors.toList());
        filltable(filteredList);
    }

    private void confirmCustomer() {
        int selectedRow = tbl_KhachHang.getSelectedRow();
        if (selectedRow != -1) {
            String tenKhachHang = tbl_KhachHang.getValueAt(selectedRow, 1).toString();
            String soDienThoai = tbl_KhachHang.getValueAt(selectedRow, 2).toString();
            bookingTable.setCustomerInfo(tenKhachHang, soDienThoai);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Swing.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_KhachHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonOutLine1 = new Swing.ButtonOutLine();
        buttonOutLine2 = new Swing.ButtonOutLine();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Stt", "Mã khách hàng", "Tên", "Số điện thoại", "Email", "Giới tính", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_KhachHang.setRowHeight(35);
        tbl_KhachHang.setSelectionBackground(java.awt.Color.gray);
        tbl_KhachHang.setShowGrid(false);
        tbl_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_KhachHang);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Tìm kiếm khách hàng");

        buttonOutLine1.setBackground(new java.awt.Color(0, 153, 0));
        buttonOutLine1.setText("Xác nhận");
        buttonOutLine1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonOutLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutLine1ActionPerformed(evt);
            }
        });

        buttonOutLine2.setBackground(new java.awt.Color(255, 0, 0));
        buttonOutLine2.setText("Hủy");
        buttonOutLine2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonOutLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutLine2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(buttonOutLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(buttonOutLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOutLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOutLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhachHangMouseClicked
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_KhachHangMouseClicked

    private void buttonOutLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine1ActionPerformed
                confirmCustomer();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOutLine1ActionPerformed

    private void buttonOutLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine2ActionPerformed
        dispose();
    }//GEN-LAST:event_buttonOutLine2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MS_ConfirmCustomer dialog = new MS_ConfirmCustomer(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.ButtonOutLine buttonOutLine1;
    private Swing.ButtonOutLine buttonOutLine2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private Swing.PanelRound panelRound1;
    private javax.swing.JTable tbl_KhachHang;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
