/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Component_Staff;

import Model.ModelLogin;
import Model.ModelNguoiDung;
import Swing.Button;
import Swing.MyPasswordField;
import Swing.MyTextField;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author LENOVO
 */
public class PanelLogin extends javax.swing.JPanel {
    //Lấy tài khoản đăng ký
    public ModelNguoiDung getUser() {
        return user;
    }

    public String getName() {
        return name;
    }

    //Lấy thông tin đăng nhập
    public ModelLogin getDataLogin() {
        return dataLogin;
    }

    private ModelNguoiDung user; //Model Tài khoản người dùng
    private String name; //Tên Khách Hàng
    private ModelLogin dataLogin; //Model thông tin đăng nhập
    private Icon hide;
    private Icon show;
    private char def;
    public PanelLogin() {
        initComponents();
    }
    
        private void initLogin(ActionListener eventLogin) {
        //Set Layout
        login.setLayout(new MigLayout("wrap", "push[center]push", "push[]25[]10[]10[]25[]push"));
        JLabel label = new JLabel("ĐĂNG NHẬP");
        label.setFont(new Font("sansserif", 1, 30));
        label.setForeground(Color.decode("#6C5B7B"));
        login.add(label);
        //TextField Email
        MyTextField txtEmail = new MyTextField();
        txtEmail.setPrefixIcon(new ImageIcon(getClass().getResource("/Icon_Staff/mail.png")));
        txtEmail.setHint("Email");
        login.add(txtEmail, "w 60%");
        //TextField Mật khẩu
        MyPasswordField txtPassword = new MyPasswordField();
        def = txtPassword.getEchoChar();
        txtPassword.setPrefixIcon(new ImageIcon(getClass().getResource("/Icon_Staff/pass.png")));
        txtPassword.setHint("Mật khẩu");
        txtPassword.setSuffixIcon(show);
        login.add(txtPassword, "w 60%");
        txtPassword.addMouseListener(new MouseAdapter() {
         
            public void mouseClicked(MouseEvent e) {
                if (txtPassword.getSuffixIcon().equals(hide)) {
                    txtPassword.setSuffixIcon(show);
                    txtPassword.setEchoChar((char) 0);

                } else {
                    txtPassword.setSuffixIcon(hide);
                    txtPassword.setEchoChar(def);
                }
            }

        });
        //Button "Quên mật khẩu"
        JButton cmdForget = new JButton("Quên mật khẩu của bạn ?");
        cmdForget.setForeground(new Color(100, 100, 100));
        cmdForget.setFont(new Font("sansserif", 1, 12));
        cmdForget.setContentAreaFilled(false);
        cmdForget.setCursor(new Cursor(Cursor.HAND_CURSOR));
        login.add(cmdForget);
        //Button "ĐĂNG NHẬP"
        Button cmd = new Button();
        cmd.setBackground(Color.decode("#6C5B7B"));
        cmd.setForeground(new Color(250, 250, 250));
        cmd.setText("ĐĂNG NHẬP");
        login.add(cmd, "w 40%, h 40");
        //Add Event cho Button "ĐANWGN NHẬP"
        cmd.addActionListener(eventLogin);
        //Add Event cho Button "ĐANWGN NHẬP"
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String email = txtEmail.getText().trim();
                String password = String.valueOf(txtPassword.getPassword());
                dataLogin = new ModelLogin(email, password);
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel login;
    // End of variables declaration//GEN-END:variables
}
